apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sparkslave
  namespace: dataprocessing
  labels:
    app: sparkslave
    tool: spark
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sparkslave
        tier: dataprocessing 
    spec:
      containers:
      - image: pblaas/spark:2.1.1
        command: [ "/usr/bin/supervisord" ]
        args: [ "--configuration=/opt/conf/slave.conf" ]
        resources:
          requests:
            cpu: "100m"
            memory: "1024Mi"
        name: sparkslave
        env:
        - name: SPARKMASTER
          value: sparkmaster
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: "1024m"

